#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="cloud-posture-watch",
        description="Cloud security posture assessment for AWS, Azure, and GCP.",
    )

    parser.add_argument(
        "--output-dir",
        default="reports",
        help="Directory where generated report files are written (default: reports).",
    )
    parser.add_argument(
        "--output-file",
        help="Explicit report file path. When provided, this takes precedence over --output-dir naming.",
    )
    parser.add_argument(
        "--format",
        choices=["json", "md"],
        default="md",
        help="Report output format (default: md).",
    )

    return parser


def _validate_output_file_path(raw_path: str) -> Path:
    path = Path(raw_path)

    # Reject obvious directory paths and existing directories.
    if raw_path.endswith(("/", "\\")) or path.is_dir():
        raise ValueError(f"Invalid --output-file '{raw_path}': path must be a file, not a directory.")

    parent = path.parent if str(path.parent) else Path(".")
    if not parent.exists() or not parent.is_dir():
        raise ValueError(
            f"Invalid --output-file '{raw_path}': parent directory does not exist ({parent})."
        )

    return path


def _resolve_output_path(args: argparse.Namespace) -> Path:
    if args.output_file:
        return _validate_output_file_path(args.output_file)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    extension = "json" if args.format == "json" else "md"
    return output_dir / f"cloud-posture-report-{timestamp}.{extension}"


def _write_report(path: Path, fmt: str, payload: dict[str, Any]) -> None:
    if fmt == "json":
        path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    else:
        path.write_text("# Cloud Posture Report\n\nGenerated by cloud-posture-watch.\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        output_path = _resolve_output_path(args)
    except ValueError as exc:
        parser.error(str(exc))

    sample_payload = {"generated_at": datetime.now(timezone.utc).isoformat()}
    _write_report(output_path, args.format, sample_payload)

    print(f"Report written: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
